Added Insert-IT as a service provider
mampfes/hacs_waste_collection_schedule pull request #1717
Opened 2024-01-24 23:26 UTC by derDeno

## Added Insert-IT as a new service provider. 
This provides a streamlined way for all Insert-IT based apps to be integrated.

Note: The benefit of this integration is the easy configuration, as it could be used with a location ID, which needs to be extracted from an url, or by simply providing street name and house number. Therefore it is easier to integrate than using static ics files.

### Currently these municipalities are supported:
- Hattingen, DE
- Herne, DE
- Kassel, DE
- Krefeld, DE
- Mannheim, DE
- Offenbach, DE

### Breaking Change
This replaces the offenbach_de source and fixes the broken mannheim source.

### Testing
Test where done successfully:
```
Testing source insert_it_de ...
  found 136 entries for Offenbach Address
  found 136 entries for Offenbach Location ID
  found 136 entries for Mannheim Address
  found 136 entries for Mannheim Location ID
```

### Misc
Two broken docs where also fixed (missing .md):
- lund_se.md
- stoke_gov_uk.md

2024-01-25 09:51 UTC, 5ila5 requested changes

2024-01-25 09:51 UTC, 5ila5 commented on doc/source/insert_it_de.md
> +Easy way to get the source arguments is to use a (desktop) browser, eg.g Google Chrome:
duplicate message

2024-01-25 09:51 UTC, 5ila5 commented on doc/source/insert_it_de.md
> +
maybe add a list of supported municipality arguments

2024-01-25 22:36 UTC, derDeno commented
requested changes were done

2024-01-26 08:36 UTC, 5ila5 approved these changes

2024-01-26 08:39 UTC, merged

2024-01-26 08:39 UTC, 5ila5 commented
Thanks for your contribtuion