Added hubert schmid gmbh
mampfes/hacs_waste_collection_schedule pull request #1924
Opened 2024-03-31 21:44 UTC by MichaelAlt

2024-04-03 11:10 UTC, 5ila5 requested changes

2024-04-03 15:28 UTC, MichaelAlt commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/api_hubert_schmid_de.py
> +
done

2024-04-03 15:28 UTC, MichaelAlt commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/api_hubert_schmid_de.py
> +        city: str | None = None,
yes actually city is the only required attribute.

2024-04-03 15:28 UTC, MichaelAlt commented on doc/source/api_hubert_schmid_de.md
> +*(String) (required)*
yes correct, fixed it.

2024-04-03 15:29 UTC, MichaelAlt commented on doc/source/api_hubert_schmid_de.md
> +# Apps by Abfall+
fixed

2024-04-04 16:13 UTC, 5ila5 approved these changes

2024-04-04 16:15 UTC, merged