Add source: Kiertokapula FI
mampfes/hacs_waste_collection_schedule pull request #2091
Opened 2024-05-16 06:53 UTC by developerfromjokela

Adding source for Finnish waste utility company Kiertokapula, which operates in cities/towns: 

- HATTULA
- HAUSJÄRVI
- HYVINKÄÄ
- HÄMEENLINNA
- JANAKKALA
- JÄRVENPÄÄ
- KERAVA
- LOPPI
- MÄNTSÄLÄ
- NURMIJÄRVI
- RIIHIMÄKI
- SÄHAS TALOYHTIÖT
- TUUSULA
- VALKEAKOSKI

2024-05-16 09:50 UTC, 5ila5 requested changes
Please run the updaete_doculinks.py script to update the markdown files ([more information](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing_source.md#update-links-in-readmemd-and-infomd))

Do you think it is obvious to users of the supported cities to know to use this source, if not you can add them to the markdown overview using the EXTRA_INFO variable (for a detailed explanation see link above)

2024-05-16 09:50 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/kiertokapula_fi.py
> +                    if service["tariff"].get("productgroup", "PER") != "PER":
I'd prefer if ... == ...: continue to reduce unnecessary indentation (the same in line 80)

2024-05-16 09:50 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/kiertokapula_fi.py
> +}
You can add test cases using 
```python
{
"bill_number": "!secret kiertonkapula_fi_bill_number"
"password": "!secret kiertonkapula_fi_bill_password"
}
```
and define these secrets in the custom_components/waste_collection_schedule/waste_collection_schedule/test/secrets.yaml file (which is not synchronized with git):

```yaml
kiertonkapula_fi_bill_number: NUMBER
kiertonkapula_fi_bill_password: PASSWORD
```

2024-05-16 09:50 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/kiertokapula_fi.py
> +        password=None,
Please do not make mandatory arguments optional

2024-05-16 09:51 UTC, developerfromjokela commented
> Please run the updaete_doculinks.py script to update the markdown files ([more information](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing_source.md#update-links-in-readmemd-and-infomd))
> 
> 
> 
> Do you think it is obvious to users of the supported cities to know to use this source, if not you can add them to the markdown overview using the EXTRA_INFO variable (for a detailed explanation see link above)

Usually users are aware which company they're using, they're getting the bill after all. I will run the doc script 👍

2024-05-19 08:44 UTC, developerfromjokela commented
@5ila5 I'm trying to run update_doculinks.py, but it throws an error on many sources:

```python
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

2024-05-20 14:18 UTC, 5ila5 commented
This error indicates you use a python version prior to 3.10 as this syntax was first introduced in 3.10

2024-05-20 14:26 UTC, 5ila5 approved these changes

2024-05-20 14:28 UTC, merged

2024-05-20 14:28 UTC, 5ila5 commented
Thanks for your contribuiton.

I run the script I needed to add Finnland to the country map as there was no Finland source prior to this one.
I reformatted your code based on .pre-commit-config.yaml