Add Rotorua lakes council (NZ) source
mampfes/hacs_waste_collection_schedule pull request #2348
Opened 2024-07-28 23:16 UTC by PMKA

This Pull request aims to introduce a source for integration with Rotorua Lakes Council rubbish collection service. The integration retrieves rubbish collection information based on a given address using the Rotorua Lakes Councils GIS API.
##### Changes:
- Added rotroua_lakes_council_nz.py
- Updated README.md,
- Added rotorua_lakes_council_nz.md

#####Test Results:

    Testing source rotorua_lakes_council_nz ...
      found 2 entries for Test1
        2024-07-31 : Rubbish and recycling [mdi:recycle]
        2024-08-07 : Rubbish only [mdi:trash-can]
      found 2 entries for Test2
        2024-07-29 : Rubbish and recycling [mdi:recycle]
        2024-08-05 : Rubbish only [mdi:trash-can]
      found 2 entries for Test3
        2024-07-30 : Rubbish only [mdi:trash-can]
        2024-08-06 : Rubbish and recycling [mdi:recycle]
      found 2 entries for Test4
        2024-07-29 : Rubbish and recycling [mdi:recycle]
        2024-08-05 : Rubbish only [mdi:trash-can]
      found 2 entries for Test5
        2024-08-01 : Rubbish and recycling [mdi:recycle]
        2024-08-08 : Rubbish only [mdi:trash-can]

2024-07-29 14:03 UTC, 5ila5 requested changes
You can use the logger by adding 
```python
import logging
_LOGGER = logging.getLogger(__name__)
```
and later log with

```python
_LOGGER.error("test ERROR") # not necessary here
# or
_LOGGER.warning("test Warning")
```

2024-07-29 22:01 UTC, PMKA commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/rotorua_lakes_council_nz.py
> +from geopy.geocoders import Nominatim
Removed geopy dependency, using direct calls to OSM instead

2024-07-29 22:11 UTC, PMKA commented
Thanks for the feedback @5ila5, have made the requested changes, let me know if there's anything else needs attention.

2024-07-30 12:57 UTC, 5ila5 commented
Do you think it would be a good idea to `Rubbish and recycling` into two events and strip the `only` from `Rubbish only`? This would make it easier to make automations on rubbish events as you do not need to define both.

But I'm fine with the current implementation if you prefer this one.

2024-07-30 12:57 UTC, 5ila5 approved these changes

2024-07-30 23:11 UTC, PMKA commented
Good call, made the change to simplify the output to be `Rubbish` and `Recycling`.

2024-07-31 08:14 UTC, 5ila5 commented
That's not really what I meant now you're just ignoring the `Rubbish` part of `Rubbish and recycling` and therefore removing information. I thought about splitting `Rubbish and recycling` up into a `Rubbish` and a `Recycling` Collection at the same day

2024-07-31 19:02 UTC, PMKA commented
> That's not really what I meant now you're just ignoring the `Rubbish` part of `Rubbish and recycling` and therefore removing information. I thought about splitting `Rubbish and recycling` up into a `Rubbish` and a `Recycling` Collection at the same day

Misunderstanding there. On days where both bin types are collected, I've now split them into separate outputs, Test results below:

Testing source rotorua_lakes_council_nz ...
  found 3 entries for Test1
    2024-08-07 : Rubbish [mdi:trash-can]
    2024-08-14 : Rubbish [mdi:trash-can]
    2024-08-14 : Recycling [mdi:recycle]
  found 3 entries for Test2
    2024-08-05 : Rubbish [mdi:trash-can]
    2024-08-12 : Rubbish [mdi:trash-can]
    2024-08-12 : Recycling [mdi:recycle]
  found 3 entries for Test3
    2024-08-06 : Rubbish [mdi:trash-can]
    2024-08-06 : Recycling [mdi:recycle]
    2024-08-13 : Rubbish [mdi:trash-can]
  found 3 entries for Test4
    2024-08-05 : Rubbish [mdi:trash-can]
    2024-08-12 : Rubbish [mdi:trash-can]
    2024-08-12 : Recycling [mdi:recycle]
  found 3 entries for Test5
    2024-08-02 : Rubbish [mdi:trash-can]
    2024-08-09 : Rubbish [mdi:trash-can]
    2024-08-09 : Recycling [mdi:recycle]

2024-08-01 09:01 UTC, merged

2024-08-01 09:02 UTC, 5ila5 commented
Thanks for your contribution. I did some minor changes to the logic and reformatted the file based on .pre-commit-config.yaml, I also run the update_docu_links.py script