Added support for OLO, Slovakia suource
mampfes/hacs_waste_collection_schedule pull request #3283
Opened 2024-12-26 16:39 UTC by mniejo

2024-12-26 18:29 UTC, 5ila5 requested changes

2024-12-26 18:29 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/olo_sk.py
> +}
please remove `enter` from the string

2024-12-26 18:29 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/olo_sk.py
> +}
Either fill in correct information or remove this Variable. This placeholder text would be shown in the configuration GUI at the moment

2024-12-26 18:29 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/olo_sk.py
> +            "authorization": "Bearer ae84ae0982c2162a81eb253765ceaa8593abd9105c71954cf5c9620b0178cbb6"
Is there another way to get this header, I don't like hard coding a Bearer token

2024-12-26 18:29 UTC, 5ila5 commented on doc/source/olo_sk.md
> +# fcc Environment (VYLOŽ SMETI APP)
Headline copy-paste leftovers?

2024-12-26 18:29 UTC, 5ila5 commented on doc/source/olo_sk.md
> +*(String) (required)*
registrationNumber missing

2024-12-26 18:29 UTC, 5ila5 commented on doc/source/olo_sk.md
> +        street: Jantarova 47
registrationNumber missing

2024-12-26 18:29 UTC, 5ila5 commented on doc/source/olo_sk.md
> +```
city is not a valid argument

2024-12-27 21:01 UTC, mniejo commented
Sorry. This PR was created by mistake on unfinished code. I'll be back with a new one in few days.

2024-12-27 21:01 UTC, closed without merging