add integration for Landkreis Rhön Grabfeld
mampfes/hacs_waste_collection_schedule pull request #396
Opened 2022-10-15 14:34 UTC by Random-Cow

Add integration for Landkreis Rhön Grabfeld.
Tested via test-script and also runs perfectly fine on my local home-assistant instance

2022-10-18 05:45 UTC, mampfes requested changes

2022-10-18 05:45 UTC, mampfes commented on doc/source/landkreis_rhoen_grabfeld.md
> +# Abfallkalender Würzburg
Wuerzburg? --> Copy-Paste Error???

2022-10-18 05:45 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_rhoen_grabfeld.py
> +        self._iconMap = {
Please make icon-map a global variable (like TEST_CASES).

2022-10-18 05:45 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_rhoen_grabfeld.py
> +            if event["muellart"] in self._iconMap:
Not sure if it is a good idea to use the icon-map to filter out waste types. I think I would prefer a blacklist.

2022-10-18 05:46 UTC, mampfes commented
Please add the new source to info.md also.

2022-10-19 14:40 UTC, Random-Cow commented on doc/source/landkreis_rhoen_grabfeld.md
> +# Abfallkalender Würzburg
Yeah, copy-paste error...

2022-10-19 14:52 UTC, merged