Added source for Maroondah City Council VIC AU
mampfes/hacs_waste_collection_schedule pull request #440
Opened 2022-11-24 06:35 UTC by DanAE111

New source for the Maroondah City Council.

2022-11-24 07:07 UTC, mampfes requested changes
Please add new source to info.md also.

2022-11-24 07:07 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/maroondah_vic_gov_au.py
> +        recyclables_date_text = response['infoPanels']['info1']['feature']['fields'][2]['value']['value']
Please do date calculation only once
`datetime.strptime(recyclables_date_text,"%A, %d %b %Y").date()`

2022-11-24 07:38 UTC, DanAE111 commented
I've gone ahead and made the changes that you requested.

2022-11-25 16:11 UTC, merged

2022-11-25 16:11 UTC, mampfes commented
Thanks for your contribution.