Added maribyrnong.py/.md to support source for Maribyrnong Council (V…
mampfes/hacs_waste_collection_schedule pull request #504
Opened 2022-12-22 21:51 UTC by dpeluso

…IC) rubbish collection, https://www.maribyrnong.vic.gov.au/Residents/Bins-and-recycling

2022-12-23 10:09 UTC, mampfes requested changes
- Please rename source (and docu) to maribyrnong_vic_gov_au
- Please add links to new source to README.md and info.md

2022-12-23 10:09 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/maribyrnong.py
> +            f"https://maribyrnong.waste-info.com.au/api/v1/properties/{property_id}.json?start={today}&end={nextmonth}",
Is there more data available than one month? If yes, please fetch all data (up to one year).

2022-12-23 10:09 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/maribyrnong.py
> +            f"https://maribyrnong.waste-info.com.au/api/v1/streets.json?locality={suburb_id}",
Please use `params` argument to pass parameters in URLs: https://requests.readthedocs.io/en/latest/user/quickstart/#passing-parameters-in-urls

2022-12-24 04:44 UTC, DanAE111 commented
Looks like Maribyrnong also uses OpenCities (you can see it mentioned on the website footer), you might find you can reference the Melton source, it could be as simple as changing the URLs to scrape the data from the Maribyrnong city council.

2022-12-24 10:27 UTC, mampfes commented
> Looks like Maribyrnong also uses OpenCities (you can see it mentioned on the website footer), you might find you can reference the Melton source, it could be as simple as changing the URLs to scrape the data from the Maribyrnong city council.

@DanAE111: Interesting! Do you have an idea how many councils using that service? Maybe it is worth to create a single source which could handle all OpenCities.

2022-12-26 08:26 UTC, DanAE111 commented
@mampfes As far as i know there are at least 3 but Granicus are touting they have over 170 government agencies using OpenCities (https://granicus.com/solution/govaccess/opencities/). If the implementation across the different agencies is the same we could certainly scrape the data with a single source.

The Maribyrnong site is different visually to Melton and Nillumbik which are the other two i know are using OpenCities in Australia. So maybe that means the source would be different in this case?

I had a quick Google and it would seem that many are similar to Melton. But it looks like the sites can change the implementation of how the waste collection lookup works, i would assume those ones are not compatible. I've listed some examples of those similar below and a few outliers i have found, it would be interesting to see if different countries using OpenCities share the address lookup which seems to be the trend here.

OpenCities Address Lookup:
https://www.murrayriver.nsw.gov.au/Our-Services/Waste-and-recycling/Find-my-bin-day
https://www.tweed.nsw.gov.au/property-rates/waste-recycling/bin-services-collection/bin-collection-days
https://www.melton.vic.gov.au/Services/Waste-and-recycling/Find-my-bin-day
https://www.nillumbik.vic.gov.au/Residents/Waste-and-recycling/Bin-collection/Check-my-bin-day

Alternative Waste Collection Lookup:
https://www.wdrc.qld.gov.au/Business-Development/Maps/Interactive-Maps
https://www.maribyrnong.vic.gov.au/Residents/Bins-and-recycling

2023-01-18 19:27 UTC, merged

2023-01-18 19:42 UTC, mampfes commented
I did the requested changes in #621