Add support for Stockport, UK
mampfes/hacs_waste_collection_schedule pull request #509
Opened 2022-12-23 18:01 UTC by MuddyRock

I may not have created the pull-request correctly - apologies if that's the case. I'm still a bit new to GitHub and Python.
There is probably a better way of iterating through the results than the one I went for. See above. Any feedback welcome.

2022-12-23 18:07 UTC, MuddyRock commented
This requires a Unique Property Reference Number (uprn) to determine the URL to use.
You can find your UPRN by going to 
https://www.stockport.gov.uk/find-your-collection-day
and entering your postcode (if you're testing this, and you live outside Stockport, try SK6 3AA), then picking your house number.
The UPRN is the final part of the URL that you are then directed to e.g.
for SK6 3AA, house number 25, you are directed to 
https://myaccount.stockport.gov.uk/bin-collections/show/10090543805
The UPRN is 10090543805

2022-12-23 18:14 UTC, mampfes requested changes
- Please rename source to stockport_gov_uk
- Please add corresponding documentation as markdown file
- Please add links to new source in README.md and info.md
--> https://github.com/mampfes/hacs_waste_collection_schedule#how-to-add-new-sources

2022-12-23 18:14 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/stockport_uk.py
> +        self._session = requests.Session()
Don't create session in __init__, but in fetch.

2022-12-23 18:14 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/stockport_uk.py
> +                    icon=ICONS[bin_name],
`icon=ICONS.get(bin_name)`
This variant doesn't crash if the bin name is missing in the dict, but fall back to default.

2022-12-23 19:56 UTC, MuddyRock commented
All requested changes made.
Specifically:
- Moved  create session to fetch
- Used correct method to check for icons
- Updated info.md
- Updated README.md
- renamed file to stockport_gov_uk.py
- Added doc file stockport_gov_uk.md in doc\source

I can't see how to re-request approval from you in GitHub for the changes.
Do I create a new pull request?

2022-12-24 10:24 UTC, mampfes commented
The diff for this PR shows major changes in README.md and info.md - maybe a problem with line endings. Check your editor and update README.md and info.md so that is shows only the newly added lines.

2023-01-18 19:54 UTC, merged

2023-01-18 20:05 UTC, mampfes commented
I did the requested changes in #622

2023-01-18 20:05 UTC, mampfes commented
Thanks for your contribution.