Add Source SRV atervinning, SE
mampfes/hacs_waste_collection_schedule pull request #518
Opened 2022-12-24 16:30 UTC by bbr111

Add Source SRV atervinning, SE

2022-12-26 10:00 UTC, mampfes requested changes
Please rename .py and .md files to srvatervinning_se

2022-12-26 10:00 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/srv_se.py
> +                dates =  {calentry["startDate"],type}
`dates` is not used

2022-12-26 13:37 UTC, bbr111 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/srv_se.py
> +                dates =  {calentry["startDate"],type}
changed in last commit

2022-12-27 08:19 UTC, merged

2022-12-27 08:19 UTC, mampfes commented
Thanks for your contribution.