Fixed source muenchenstein_bl
mampfes/hacs_waste_collection_schedule pull request #600
Opened 2023-01-10 20:34 UTC by r3turnNull

Fixed the URL for the collection dates as it was changed by the municipality.

2023-01-11 06:14 UTC, mampfes requested changes
This is a new source, right? Please add a md file in doc folder and run update_docu_links.py to update README.md and info.md

2023-01-11 06:14 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/muenchenstein_ch.py
> +TITLE = "Abfallsammlung Münchenstein"
Remove Abfallsammlung - all swiss sources just use the name of the municipality.

2023-01-11 06:14 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/muenchenstein_ch.py
> +IconMap = {
IconMap -> ICON_MAP

2023-01-11 06:14 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/muenchenstein_ch.py
> +URL = "https://www.muenchenstein.ch/abfuhrdaten"
Remove abfuhrdaten from URL.

2023-01-11 07:03 UTC, dt215git commented
muenchenstein was removed in 1.32 due to a broken source. I guess that means the md, readme, and info files also changed.

2023-01-11 12:08 UTC, mampfes commented
> muenchenstein was removed in 1.32 due to a broken source. I guess that means the md, readme, and info files also changed.

Ah, thanks! That's why this sounded so familiar to me :-) 

In the meantime some refactorings happend, therefore they have to be retightened in the source code. I already added comments to the PR. And the docu has to be recovered and potentially adapted.

2023-01-15 09:51 UTC, merged

2023-01-15 09:58 UTC, mampfes commented
I did the requested changes by myself.

2023-01-15 09:58 UTC, mampfes commented
Thanks for your contribution.