fixed awido_de to work corrcectly wihthout the street parameter
mampfes/hacs_waste_collection_schedule pull request #777
Opened 2023-03-19 16:36 UTC by 5ila5

fixed #737 
There was a logic error if no street where given it tried to get the id using the not existing street which leads to a wrong id given to the last request.

2023-03-19 18:59 UTC, mampfes requested changes

2023-03-19 18:59 UTC, mampfes commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py
> +        print(r.url)
Please remove the debug output.

2023-03-19 19:31 UTC, 5ila5 commented on custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py
> +        print(r.url)
oh I'm sorry must have overseen it

2023-03-20 07:33 UTC, merged

2023-03-20 07:34 UTC, mampfes commented
Thanks, 5ila5.